### ISSUE TITLE
Tableau Auto Refresh with less than 1 Min

### ISSUE THREAD

**Issue by Soumyamondal123** [tableau/create-tableau-dashboard-extension#1]
Do we have any Python code or any Js Code which will automatically hit the Refresh button on the Tableau Online or Tableau Server Published Reports? if any such code, it will help to show the Published Data in a Monitor live connection. So each end user who has access on the reports can put in their monitor get live data automatically.

**Comment by takashibinns** [comment]
This question doesn't seem to have anything to do with this repository, instead you are asking about creating a solution for updating tableau dashboards in a non-interactive format (live monitor).  It could be possible to build a dashboard extension to do this, but that behavior will end up [getting blocked on tableau cloud](https://tableau.github.io/extensions-api/docs/interfaces/datasource.html#refreshasync).

Instead, a better approach would be to develop a simple web app that uses the REST API to fetch an image of the dashboard you want to show.  Then you could refresh (fetch again) the viz every X minutes, by making another REST API call.  This approach will not keep an open session with Tableau Server/Cloud so it's much more efficient, and it's not like you need an interactive session anyways if it's displayed on a monitor.
